### PR TITLE
Jenkins deploy

### PR DESCRIPTION
**Pull request by brosaaj**
Automatic deployment decoupled from instance provisioning

### CODE REVIEW

**Comment by brosaaj** [comment]
run_jenkins_ci

**Comment by brosaaj** [comment]
run_jenkins_ci

**Comment by brosaaj** [comment]
run_jenkins_ci

**Comment by brosaaj** [comment]
run_jenkins_ci

**Comment by brosaaj** [comment]
run_jenkins_ci

**Comment by brosaaj** [comment]
run_jenkins_ci

**Review by rmukhammadaliyev — APPROVED** [review]
Looks good to me

**Comment by brosaaj** [comment]
run_jenkins_ci

**Pull request merged**
